/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blocodenotas;

import java.awt.Font;
import java.io.File;
import java.io.RandomAccessFile;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author TRISTAO
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_area = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jM_novo = new javax.swing.JMenuItem();
        jM_abrir = new javax.swing.JMenuItem();
        jM_salvar = new javax.swing.JMenuItem();
        jM_salvarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jM_fonte = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jT_area.setColumns(20);
        jT_area.setRows(5);
        jScrollPane1.setViewportView(jT_area);

        jMenu1.setText("Arquivo");

        jM_novo.setText("Novo");
        jM_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_novoActionPerformed(evt);
            }
        });
        jMenu1.add(jM_novo);

        jM_abrir.setText("Abrir...");
        jM_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(jM_abrir);

        jM_salvar.setText("Salvar");
        jM_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_salvarActionPerformed(evt);
            }
        });
        jMenu1.add(jM_salvar);

        jM_salvarComo.setText("Salvar como...");
        jMenu1.add(jM_salvarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Formatar");

        jM_fonte.setText("Fonte...");
        jM_fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_fonteActionPerformed(evt);
            }
        });
        jMenu3.add(jM_fonte);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_abrirActionPerformed
        JFileChooser c = new JFileChooser();

        c.showOpenDialog(this);
        File file = c.getSelectedFile();

        try {
            Path path = Paths.get(file.getAbsolutePath());
            String returno = new String(Files.readAllBytes(path));
            jT_area.setText(returno);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Não conseguimos carregar seu arquivo!");
        }


    }//GEN-LAST:event_jM_abrirActionPerformed

    private void jM_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_novoActionPerformed
        jT_area.setText("");
    }//GEN-LAST:event_jM_novoActionPerformed

    private void jM_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_salvarActionPerformed

        /* JFileChooser fileChooser = new JFileChooser();
        String NomeArq = fileChooser.getSelectedFile().getAbsolutePath(); // pego o path + o nome do arquivo
        if (!NomeArq.endsWith(".txt")){                                  // digitado no campo "salvar" do JFileChooser
        NomeArq += ".txt";
        }
        File arquivo2 = new File(NomeArq);
        boolean ok = fileName.renameTo(arquivo2); // renomeio o arquivo para  "NomeArq"
        if(ok) System.out.println("Arquivo renomeado com sucesso " + NomeArq);
        else
        System.out.println("Erro");*/
        JFileChooser arquivo = new javax.swing.JFileChooser();
        arquivo.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        int resultadoArq = arquivo.showSaveDialog(null);
        if (resultadoArq == javax.swing.JFileChooser.CANCEL_OPTION) {
            return;
        }
        File arquivoNome = arquivo.getSelectedFile();
        if (arquivoNome == null || arquivoNome.getName().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Nome de"
                    + "Arquivo Inválido",
                    "Nome de Arquivo Inválido", javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } else {
            try {
                RandomAccessFile file = new RandomAccessFile(arquivoNome, "rw");

                file.writeUTF(jT_area.getText().trim());
                file.close();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jM_salvarActionPerformed

    private void jM_fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_fonteActionPerformed
        Fonte frame = new Fonte();
        frame.setVisible(true);
    }//GEN-LAST:event_jM_fonteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jM_abrir;
    private javax.swing.JMenuItem jM_fonte;
    private javax.swing.JMenuItem jM_novo;
    private javax.swing.JMenuItem jM_salvar;
    private javax.swing.JMenuItem jM_salvarComo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_area;
    // End of variables declaration//GEN-END:variables
}
