/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareacademia;

/**
 *
 * @author TRISTAO
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btn_usuario = new javax.swing.JMenuItem();
        btn_registrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        usuario_CM = new javax.swing.JMenuItem();
        cadastrar_CM = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_logoff = new javax.swing.JMenuItem();
        sair_tela = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Avaliação Fisica");

        btn_usuario.setText("Usuarios");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        jMenu2.add(btn_usuario);

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_registrar);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Cadastro/Mensalidades");

        usuario_CM.setText("Usuarios");
        usuario_CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_CMActionPerformed(evt);
            }
        });
        jMenu4.add(usuario_CM);

        cadastrar_CM.setText("Cadastrar");
        cadastrar_CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_CMActionPerformed(evt);
            }
        });
        jMenu4.add(cadastrar_CM);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Sair");

        btn_logoff.setText("Logoff");
        btn_logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoffActionPerformed(evt);
            }
        });
        jMenu3.add(btn_logoff);

        sair_tela.setText("Sair");
        sair_tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_telaActionPerformed(evt);
            }
        });
        jMenu3.add(sair_tela);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_CMActionPerformed
         Cadastro frame = new Cadastro();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrar_CMActionPerformed

    private void sair_telaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_telaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sair_telaActionPerformed

    private void btn_logoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoffActionPerformed
         Inicio frame = new Inicio();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoffActionPerformed

    private void usuario_CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_CMActionPerformed
        
         Cadastrados frame = new Cadastrados();
        frame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_usuario_CMActionPerformed

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
            PesquisarAvalicao frame = new PesquisarAvalicao();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
           Avaliacao_Fisica frame = new Avaliacao_Fisica();
        frame.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_logoff;
    private javax.swing.JMenuItem btn_registrar;
    private javax.swing.JMenuItem btn_usuario;
    private javax.swing.JMenuItem cadastrar_CM;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sair_tela;
    private javax.swing.JMenuItem usuario_CM;
    // End of variables declaration//GEN-END:variables
}
