/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.pedidos;

import insercao.BD_tratamentos;
import insercao.Control;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import principal.AddUsuario;
import principal.Cadastrar_Cliente;
import principal.Confirm_Caixa;

import principal.Inicio;
import principal.Lista_Clientes;
import principal.Lista_Usuario;
import principal.Menuinicio;
import principal.RemoveUsuario;
import principal.Usuario;

/**
 *
 * @author Filipe
 */
public class Pedido_balcao extends javax.swing.JFrame
{

  
   // Pedido_Class venda = new Pedido_Class();
   String nomeusuario;
 double total;
  String recebeString="<html>";
    public Pedido_balcao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("projetopizza?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        produtosQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery.getResultList();
        cVendaQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM CVenda c");
        cVendaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cVendaQuery.getResultList();
        produtosQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produtos p");
        produtosList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery1.getResultList();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPedido = new javax.swing.JTable();
        lblPedidos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelPreco = new javax.swing.JTable();
        apagar = new javax.swing.JButton();
        btnEncaminhar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNome1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cxCredito = new javax.swing.JCheckBox();
        cxDebito = new javax.swing.JCheckBox();
        cxVaVr = new javax.swing.JCheckBox();
        cxImpresso = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtquant = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTobs = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRBPequeno = new javax.swing.JRadioButton();
        jRBMedio = new javax.swing.JRadioButton();
        jRBGrande = new javax.swing.JRadioButton();
        jRBMeio = new javax.swing.JRadioButton();
        lblTotal = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelsalvacao = new javax.swing.JLabel();
        jBConfirma = new javax.swing.JButton();
        jlHora = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMInicio2 = new javax.swing.JMenuItem();
        jMPedidos = new javax.swing.JMenu();
        jMPedidos2 = new javax.swing.JMenuItem();
        jMenu_balcao = new javax.swing.JMenuItem();
        jMenu_Pedidos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jM_RemoveUser = new javax.swing.JMenuItem();
        jM_AddUser = new javax.swing.JMenuItem();
        jM_ListaUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMCadastrarCliente = new javax.swing.JMenuItem();
        jM_ListaCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMCaixa2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setFocusCycleRoot(true);
        jPanel4.setFocusTraversalPolicyProvider(true);

        jTabelaPedido.setBackground(new java.awt.Color(255, 204, 102));
        jTabelaPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 255, 153)));
        jTabelaPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto", "Quant", "Tamanho", "Preço", "Obs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPedido.setToolTipText("Selecione todas as colunas para apagar");
        jTabelaPedido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabelaPedidoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTabelaPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaPedidoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaPedido);
        if (jTabelaPedido.getColumnModel().getColumnCount() > 0) {
            jTabelaPedido.getColumnModel().getColumn(0).setResizable(false);
            jTabelaPedido.getColumnModel().getColumn(1).setResizable(false);
            jTabelaPedido.getColumnModel().getColumn(2).setResizable(false);
            jTabelaPedido.getColumnModel().getColumn(3).setResizable(false);
            jTabelaPedido.getColumnModel().getColumn(4).setResizable(false);
            jTabelaPedido.getColumnModel().getColumn(5).setResizable(false);
        }

        lblPedidos.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblPedidos.setForeground(new java.awt.Color(204, 204, 204));

        jTabelPreco.setToolTipText("Valor/Quantidade do Volume");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, produtosList1, jTabelPreco);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idProduto}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nmProduto}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${obsProduto}"));
        columnBinding.setColumnName("Observação");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorMedia}"));
        columnBinding.setColumnName("V. Media/600ml");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorMeia}"));
        columnBinding.setColumnName("V. Meia/350");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorPequena}"));
        columnBinding.setColumnName("V. Pqn/235ml");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorGrande}"));
        columnBinding.setColumnName("V. Grnd/2L");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTabelPreco.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabelPrecoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(jTabelPreco);

        apagar.setText("Apagar");
        apagar.setToolTipText("Selecione para apagar");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        btnEncaminhar.setText("<html><hr><h4>Encaminhar Pedido");
        btnEncaminhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncaminharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(281, 281, 281)
                            .addComponent(btnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apagar)
                    .addComponent(btnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNome1.setToolTipText("Nome do cliente");

        jLabel3.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOME");

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel7.setText("TIPO DE PAGAMENTO");

        cxCredito.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        cxCredito.setText("C.CRÉDITO");
        cxCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCreditoActionPerformed(evt);
            }
        });

        cxDebito.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        cxDebito.setText("C.DÉBITO");
        cxDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDebitoActionPerformed(evt);
            }
        });

        cxVaVr.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        cxVaVr.setText("VR/VA");

        cxImpresso.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        cxImpresso.setText("IMPRESSO");
        cxImpresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxImpressoMouseClicked(evt);
            }
        });
        cxImpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxImpressoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel5.setText("TROCO  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cxCredito)
                                        .addGap(18, 18, 18)
                                        .addComponent(cxDebito)
                                        .addGap(18, 18, 18)
                                        .addComponent(cxVaVr))
                                    .addComponent(cxImpresso))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxCredito)
                    .addComponent(cxDebito)
                    .addComponent(cxVaVr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(cxImpresso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel4.setText("C. PRODUTO");

        jLabel8.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel8.setText("TAMANHO");

        jLabel11.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel11.setText("PEDIDO");

        jTobs.setColumns(20);
        jTobs.setRows(5);
        jScrollPane2.setViewportView(jTobs);

        jLabel10.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel10.setText("OBSERVAÇÃO");

        jLabel12.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel12.setText("QUANTIDADE");

        buttonGroup1.add(jRBPequeno);
        jRBPequeno.setText("Pequeno");

        buttonGroup1.add(jRBMedio);
        jRBMedio.setText("Medio");
        jRBMedio.setToolTipText("Normal");

        buttonGroup1.add(jRBGrande);
        jRBGrande.setText("Grande");

        buttonGroup1.add(jRBMeio);
        jRBMeio.setText("Meio");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 153));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBPequeno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBMedio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBGrande)
                                .addGap(18, 18, 18)
                                .addComponent(jRBMeio))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBPequeno)
                    .addComponent(jRBMedio)
                    .addComponent(jRBGrande)
                    .addComponent(jRBMeio))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAdd1.setText("Adicionar");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome1)
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel2.setText("BALCÃO");

        labelsalvacao.setText(".");

        jBConfirma.setText("CONFIRMAR PEDIDO");
        jBConfirma.setToolTipText("");
        jBConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBConfirmaMouseReleased(evt);
            }
        });
        jBConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmaActionPerformed(evt);
            }
        });

        jlHora.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlHora.setForeground(new java.awt.Color(0, 0, 102));
        jlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jldata.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jldata.setForeground(new java.awt.Color(0, 0, 102));
        jldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCadastro.setText("Cadastrar Cliente");
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastroMouseClicked(evt);
            }
        });
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jMInicio.setText("Inicio");

        jMInicio2.setText("Inicio");
        jMInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInicio2ActionPerformed(evt);
            }
        });
        jMInicio.add(jMInicio2);

        jMenuBar2.add(jMInicio);

        jMPedidos.setText("Pedidos");
        jMPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPedidosActionPerformed(evt);
            }
        });

        jMPedidos2.setText("Pedido Entrega");
        jMPedidos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPedidos2ActionPerformed(evt);
            }
        });
        jMPedidos.add(jMPedidos2);

        jMenu_balcao.setText("Pedido Balcão");
        jMenu_balcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_balcaoActionPerformed(evt);
            }
        });
        jMPedidos.add(jMenu_balcao);

        jMenu_Pedidos.setText("Cancelar Pedido");
        jMenu_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_PedidosActionPerformed(evt);
            }
        });
        jMPedidos.add(jMenu_Pedidos);

        jMenuBar2.add(jMPedidos);

        jMenu1.setText("Usuarios");

        jM_RemoveUser.setText("Remover usuário");
        jM_RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_RemoveUserActionPerformed(evt);
            }
        });
        jMenu1.add(jM_RemoveUser);

        jM_AddUser.setText("Adicionar usuário");
        jM_AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_AddUserActionPerformed(evt);
            }
        });
        jMenu1.add(jM_AddUser);

        jM_ListaUsuario.setText("Usuarios cadastrados");
        jM_ListaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_ListaUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jM_ListaUsuario);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Cadastrar Cliente");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMCadastrarCliente.setText("Cadastrar");
        jMCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMCadastrarCliente);

        jM_ListaCliente.setText("Lista de Clientes");
        jM_ListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_ListaClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jM_ListaCliente);

        jMenuBar2.add(jMenu2);

        jMenu4.setText("Caixa");

        jMCaixa2.setText("Caixa");
        jMCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCaixa2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMCaixa2);

        jMenuBar2.add(jMenu4);

        jMenu3.setText("Sair");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelsalvacao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jBConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jldata, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastro)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBConfirma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jldata, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(labelsalvacao)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
      Pedido_Class venda = new Pedido_Class();
        
        
        
        String codigo = txtcodigo.getText().trim();
        String quant = txtquant.getText().trim();
        String nmProduto;
        String preco;      
        String obs;
        String tamanho = null;
        
        tamanho = (jRBPequeno.isSelected())?"P":tamanho;
        tamanho = (jRBMedio.isSelected())?"Med":tamanho;
        tamanho = (jRBGrande.isSelected())?"G":tamanho;
        tamanho = (jRBMeio.isSelected())?"Meio":tamanho;
        venda.tamanho = tamanho;
      
        nmProduto = venda.nome_produto(codigo).trim();//metodo para dar nome apartir do codigo
        preco = venda.calcula_Pizza(codigo, quant,tamanho);//metodo para calcular o total
        obs = jTobs.getText();
         
        //add in tabel
         DefaultTableModel val =(DefaultTableModel) jTabelaPedido.getModel();//classe para alimentar a tabela
         val.addRow(new String[]{codigo,nmProduto,quant,tamanho,preco,obs});//um array com 5 colunas        

       
         
         
         //colocando na lista
         status();
         pedido();
         tempo();
         cliente();
       try {
           BD_tratamentos.conecta();
           //venda.ProdutoVendido("1", codigo, tamanho, quant, obs);
           BD_tratamentos. produtoVendido("1", codigo, tamanho, quant, obs);
       } catch (Exception ex) {
           Logger.getLogger(Pedido_balcao.class.getName()).log(Level.SEVERE, null, ex);
       }
        //limpar o campo
        txtcodigo.setText("");
        txtquant.setText("");
        jTobs.setText(""); 
        txtcodigo.requestFocus();
      
        
        //CALCULAR O TOTAL NO LABEL
        double x= Double.parseDouble(preco);
         total=total+ x;
         lblTotal.setText("R$ "+total);
        
    
         
         
         recebeString = recebeString+ "<html></br><b>Cod:</b> " +codigo+" | <b>Produto:</b> "+nmProduto+" | <b>Quant:</b> "
         +quant+" | <b>Tamanho:</b> "+tamanho+" | <b>Preço:</b> "+preco+"</br> | <b>Obs:</b> "+obs+"</br><hr></br>";
         
      
        
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void jTabelaPedidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabelaPedidoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelaPedidoAncestorAdded

    private void jTabelaPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaPedidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelaPedidoKeyPressed

    private void cxCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCreditoActionPerformed
        // TODO add your handling code here:

        // index2 = jCBCredito_Pagamento.getSelectedIndex();

    }//GEN-LAST:event_cxCreditoActionPerformed

    private void cxDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDebitoActionPerformed
        // TODO add your handlilblPedidore:
    }//GEN-LAST:event_cxDebitoActionPerformed

    private void cxImpressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxImpressoMouseClicked
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null,"CAMPO DE TROCO É OBRIGATORIO");
    }//GEN-LAST:event_cxImpressoMouseClicked

    private void cxImpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxImpressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxImpressoActionPerformed

    private void jBConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmaActionPerformed
        // TODO add your handling code here:
        Pedido_Class venda = new Pedido_Class();
        double troco_pag;
        venda.tipo_pag = "";
        //--------------------------------------------------------
        // ---RECEBER OS DADOS DO CLIENTE
        venda.nome= (txtNome1.getText());
 // ---  RECEBER O TIPO DE PAGAMENTO
        if (cxCredito.isSelected()){
            venda.tipo_pag = venda.tipo_pag + " Cartão de Crédito / ";
        }
        if (cxDebito.isSelected()){
            venda.tipo_pag = venda.tipo_pag + " Cartão de Débito / ";
        }
        if (cxVaVr.isSelected()){
            venda.tipo_pag = venda.tipo_pag + " Cartão VA ou VR / ";
        }

        if (cxImpresso.isSelected()){
            troco_pag =  Double.parseDouble(txtTroco.getText());
            venda.tipo_pag = venda.tipo_pag + " Em dinheiro. Troco para: R$" + troco_pag;
        }else{}
        
        //trantando horas
       venda.hora = jlHora.getText();
       venda.data = jldata.getText();  
       venda.usuario = jLUsuario.getText();
///----------PEDIDO 
        int confirme = JOptionPane.showConfirmDialog(null,"<html><p>"+"Usuário:"+venda.usuario+"<br>Data:"+venda.data+"<br>Hora: "+venda.hora+"<hr><br>Cliente: " 
              +venda.nome + "<hr><br>Pagamento:"+venda.tipo_pag + "<hr><h3>Pedido:</h3> <br>"+recebeString
              +"<h3 bgcolor=yellow>Total: R$"+ total+"</h3>" ," Confirmar",JOptionPane.YES_NO_OPTION);
        
        if(JOptionPane.YES_OPTION == confirme){
            JOptionPane.showMessageDialog(null,"<html><h3>Pedido realizado com sucesso!</br><h5> prazo de 30minutos ");
         
            
  ///COLOCANDO OS DADOS NO BANCO DE DADOS          
            String iD_User = null;
            //pegando o id do usuario pelo nome
            String nomeUsuario = (jLUsuario.getText());
            try {
               BD_tratamentos.conecta();
             iD_User =   BD_tratamentos.consultarID(nomeUsuario);
             
            } catch (Exception ex) {
                Logger.getLogger(Pedido_balcao.class.getName()).log(Level.SEVERE, null, ex);
          
            }
           
            try {
                  BD_tratamentos.conecta();
                BD_tratamentos.recebeVenda(iD_User, venda.data, venda.hora,total,"Balcão");//
                
                
         iD_User = "";                
         txtNome1.setText(" ");
        
        lblTotal.setText("");
        total = 0;//zerar variavel global
        recebeString = "";
         Menuinicio frame =new Menuinicio();
         frame.setVisible(true);
         dispose();
                //Control.InsereDados(venda.nome, venda.endereco, venda.telefone, venda.tipo_pag, auxiliar[1], auxiliar[2]
                //  , auxiliar[3], auxiliar[4],x);
            } catch (Exception ex) {
                Logger.getLogger(Pedido_balcao.class.getName()).log(Level.SEVERE, null, ex);
                  txtNome1.setText(" ");
  
        lblTotal.setText("");
        total = 0;//zerar variavel global
        recebeString = "";
         Menuinicio frame =new Menuinicio();
         frame.setVisible(true);
         dispose();
            }

      
        }

        
    }//GEN-LAST:event_jBConfirmaActionPerformed

    private void jBConfirmaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConfirmaMouseReleased
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_jBConfirmaMouseReleased

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        // TODO add your handling code here:

        ((DefaultTableModel) jTabelaPedido.getModel()).removeRow(jTabelaPedido.getSelectedRow());
        lblTotal.setText("");
        total = 0;//zerar variavel global
        recebeString = "";
    }//GEN-LAST:event_apagarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Usuario classe = new Usuario();
       String usu = classe.danome();
        jLUsuario.setText(usu);
  
         //data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new  SimpleDateFormat("dd/MM/yy");//instancio a classe format e determinando um formato 
        jldata.setText(formato.format(dataSistema));//seto a data do sistema com o formato do metodo instanciado
       
        
        //hora       
        Timer timer = new Timer(1000,new Pedido_balcao.hora());//instanciando a classe Timer
        timer.start();
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseClicked
btnCadastro.setBackground(Color.BLUE);    
    }//GEN-LAST:event_btnCadastroMouseClicked

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        
        Cadastrar_Cliente frame = new Cadastrar_Cliente();
        frame.setVisible(true);
        dispose();//toccar
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void jTabelPrecoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabelPrecoAncestorAdded
        // TODO add your handling code here:
        ArrayList<String> produto = new ArrayList<String>();
        DefaultTableModel val =(DefaultTableModel) jTabelPreco.getModel();//classe para alimentar a tabela
        produto.add("P.Calabresa");
        produto.add("P.Queijo");
        produto.add("P.Frango");
        produto.add("P.Carne");
        produto.add("P.Portuguesa");
        produto.add("Coca Cola");
        produto.add("Guarana");

        ArrayList<Double> valorpe= new ArrayList<Double>();
        ArrayList<Double> valormedia= new ArrayList<Double>();
        ArrayList<Double> valorgrande= new ArrayList<Double>();
        ArrayList<Double> valormeio = new ArrayList<Double>();

        for(int i =1;i<=5;i++){
            valorpe.add(10.5);
            valormedia.add(25.0);
            valorgrande.add(35.0);
            valormeio.add(13.5);

        }

        for(int i =0;i<=1;i++){
            valorpe.add(3.0);
            valormedia.add(5.0);
            valorgrande.add(7.0);
            valormeio.add(2.5);
        }

        //passar para tabela

        for(int i =0;i<=7;i++){
            val.addRow(new String[]{Integer.toString(i),produto.get(i),Double.toString(valorpe.get(i)),Double.toString(valormedia.get(i)),
                Double.toString(valorgrande.get(i)),Double.toString(valormeio.get(i))});

        }

        jTabelPreco.requestFocus();
    }//GEN-LAST:event_jTabelPrecoAncestorAdded

    private void btnEncaminharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncaminharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncaminharActionPerformed

    private void jMInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInicio2ActionPerformed
        // TODO add your handling code here:
        Menuinicio frame = new Menuinicio();
        frame.setVisible(true);
           String nome;
        nome = jLUsuario.getText().toString();
        dispose();
    }//GEN-LAST:event_jMInicio2ActionPerformed

    private void jMPedidos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPedidos2ActionPerformed
        // TODO add your handling code here:
        Pedido_entrega frame = new Pedido_entrega();
        frame.setVisible(true);
        String nome;
        nome = jLUsuario.getText();
        dispose();

    }//GEN-LAST:event_jMPedidos2ActionPerformed

    private void jMenu_balcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_balcaoActionPerformed
        // TODO add your handling code here:
        Pedido_balcao frame = new Pedido_balcao();

        frame.setVisible(true);
     //   String nome;
        //nome = jLUsuario.getText().toString();
     //   frame.recebeNome(nome);
        dispose();
    }//GEN-LAST:event_jMenu_balcaoActionPerformed

    private void jMenu_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_PedidosActionPerformed
        // TODO add your handling code here:
        Pedidos_Lista frame = new Pedidos_Lista();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_PedidosActionPerformed

    private void jMPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMPedidosActionPerformed

    private void jM_RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_RemoveUserActionPerformed
        // TODO add your handling code here:

        String nome;
        String senha;
        boolean confirma = false;

        nome = JOptionPane.showInputDialog("<html><h3>Login do adiministrador:");
        senha = JOptionPane.showInputDialog("<html><h3>Senha do adiministrador:");

        try {
            BD_tratamentos.conecta();

            if (!BD_tratamentos.confirmaLogin(nome,senha)){
                JOptionPane.showMessageDialog(null, "<html><h3>Acesso Negado para o usuário!");

            } else{

                JOptionPane.showMessageDialog(null, "<html><h3>Acesso Liberado para o usúario "+nome+"!");
                RemoveUsuario frame = new RemoveUsuario();
                frame.setVisible(true);
                dispose();

            }
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Usuario nao encontrado no banco de dados: "+ex);
        }
    }//GEN-LAST:event_jM_RemoveUserActionPerformed

    private void jM_AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_AddUserActionPerformed
        // TODO add your handling code here:

        String nome;
        String senha;
        boolean confirma = false;

        nome = JOptionPane.showInputDialog("<html><h3>Login do adiministrador:");
        senha = JOptionPane.showInputDialog("<html><h3>Senha do adiministrador:");

        try {
            BD_tratamentos.conecta();

            if (!BD_tratamentos.confirmaLogin(nome,senha)){
                JOptionPane.showMessageDialog(null, "<html><h3>Acesso Negado para o usuário!");

            } else{

                JOptionPane.showMessageDialog(null, "<html><h3>Acesso Liberado para o usúario "+nome+"!");
                AddUsuario frame = new AddUsuario();
                frame.setVisible(true);
                dispose();

            }
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Usuario nao encontrado no banco de dados: "+ex);
        }
    }//GEN-LAST:event_jM_AddUserActionPerformed

    private void jM_ListaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_ListaUsuarioActionPerformed
        // TODO add your handling code here:
        String nome;
        String senha;
        boolean confirma = false;

        nome = JOptionPane.showInputDialog("<html><h3>Login do adiministrador:");
        senha = JOptionPane.showInputDialog("<html><h3>Senha do adiministrador:");

        try {
            BD_tratamentos.conecta();

            if (!BD_tratamentos.confirmaLogin(nome,senha)){
                JOptionPane.showMessageDialog(null, "<html><h3>Acesso Negado para o usuário!");

            } else{

                JOptionPane.showMessageDialog(null, "Acesso Liberado para o usúario "+nome+"!");
                Lista_Usuario frame = new Lista_Usuario();
                frame.setVisible(true);
                dispose();

            }
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Usuario nao encontrado no banco de dados: "+ex);
        }
    }//GEN-LAST:event_jM_ListaUsuarioActionPerformed

    private void jMCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarClienteActionPerformed
        // TODO add your handling code here:
        Cadastrar_Cliente frame = new Cadastrar_Cliente();
        frame.setVisible(true);
        dispose();//toccar
    }//GEN-LAST:event_jMCadastrarClienteActionPerformed

    private void jM_ListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_ListaClienteActionPerformed
        // TODO add your handling code here:
        Lista_Clientes frame = new Lista_Clientes();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jM_ListaClienteActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCaixa2ActionPerformed
        // TODO add your handling code here:

        Confirm_Caixa frame = new Confirm_Caixa();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMCaixa2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Inicio frame = new Inicio();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_balcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_balcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_balcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_balcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido_balcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagar;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEncaminhar;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.util.List<principal.pedidos.CVenda> cVendaList;
    private javax.persistence.Query cVendaQuery;
    private javax.swing.JCheckBox cxCredito;
    private javax.swing.JCheckBox cxDebito;
    private javax.swing.JCheckBox cxImpresso;
    private javax.swing.JCheckBox cxVaVr;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBConfirma;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMCadastrarCliente;
    private javax.swing.JMenuItem jMCaixa2;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenuItem jMInicio2;
    private javax.swing.JMenu jMPedidos;
    private javax.swing.JMenuItem jMPedidos2;
    private javax.swing.JMenuItem jM_AddUser;
    private javax.swing.JMenuItem jM_ListaCliente;
    private javax.swing.JMenuItem jM_ListaUsuario;
    private javax.swing.JMenuItem jM_RemoveUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenu_Pedidos;
    private javax.swing.JMenuItem jMenu_balcao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBGrande;
    private javax.swing.JRadioButton jRBMedio;
    private javax.swing.JRadioButton jRBMeio;
    private javax.swing.JRadioButton jRBPequeno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTabelPreco;
    private javax.swing.JTable jTabelaPedido;
    private javax.swing.JTextArea jTobs;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jldata;
    private javax.swing.JLabel labelsalvacao;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblTotal;
    private java.util.List<principal.pedidos.Produtos> produtosList;
    private java.util.List<principal.pedidos.Produtos> produtosList1;
    private javax.persistence.Query produtosQuery;
    private javax.persistence.Query produtosQuery1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtquant;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

  

  //tabelas
    public String status() {
   String status= "Preparando";
       return status;
        
    }

   
    public String pedido() {
        Pedido_Class venda = new Pedido_Class();
   String pedido= venda.nome_produto(txtcodigo.getText().trim()).trim();
        return pedido;
    }

    
    public String tempo() {
    String tempo= jlHora.getText();
    return tempo;
    }

 
    public String cliente() {
        
        String cliente=txtNome1.getText();
        return cliente;
    }
    
    
 

  
    
 

 

class hora implements ActionListener{
    
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        jlHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        
        
    }
    
}
  private void btnCadastroMouseMoved(java.awt.event.MouseEvent evt) {
        btnCadastro.setBackground(Color.BLUE);
    }
    // quando o ponteiro do mouse sai de cima do botão
    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
        btnCadastro.setBackground(Color.RED);
    }


}
